version: 2
jobs:
  build:
    docker:
      # the image running the build
      - image: 497387467775.dkr.ecr.us-east-1.amazonaws.com/oz-base-test:0.9.2
    steps:
      - checkout

      # set up authentication to access private npm repo
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc

      # restore npm cache
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: yarn install

      # save npm cache to speed up future builds
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      # run tests
      - run: mkdir ./junit
      - run:
          command: node_modules/gulp/bin/gulp.js test
          environment:
            MOCHA_FILE: ./junit/test-results.xml

      - store_test_results:
          path: ./junit

      - store_artifacts:
          path: ./junit

      # deploy if we're in master
      - deploy:
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "We're on master so we're publishing"
              yarn publish --non-interactive
            else
              echo "We're not on master so we're not publishing"
            fi
